project:
  type: website
  output-dir: docs

website:
  title: "Anna Tackabery"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - education.qmd

# supplying a light ("minty") and dark ("slate") theme to toggle between
format:
  html:
    theme: 
      light: yeti
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

